- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install packages list
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3
      - python3-pip
      - python-setuptools
  - name: Get Docker APT Key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add APT Repo
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  - name: Install docker-ce using APT
    apt:
     update_cache: true
     name: docker-ce
     state: latest
  - name: Docker is started
    service:
      name: docker
      state: started
  - name: Install pip for Docker
    pip:
      name: docker
      executable: pip3
  - name: Allow User Access
    user:
      name: bilalmustafa1797
      groups: docker
      append: yes
  - name: restart connection to ensure user can complete docker commands
    meta: reset_connection
